export const CREATING_BREED = "CREATING_BREED";
export const CREATE_BREED_DB_SUCCESS = "CREATE_BREED_DB_SUCCESS";
export const CREATE_BREED_DB_ERROR = "CREATE_BREED_DB_ERROR";
export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_BREEDS_BY_NAME = "GET_BREEDS_BY_NAME";
export const GET_BREED_BY_ID = "GET_BREED_BY_ID";
