//Breed types
export const LOADING_DB_BREEDS = "LOADING_DB_BREEDS";
export const CREATE_BREED_DB_SUCCESS = "CREATE_BREED_DB_SUCCESS";
export const CREATE_BREED_DB_ERROR = "CREATE_BREED_DB_ERROR";
export const GET_ALL_BREEDS_SUCCESS = "GET_ALL_BREEDS_SUCCESS";
export const GET_ALL_BREEDS_ERROR = "GET_ALL_BREEDS_ERROR";
export const GET_BREEDS_BY_NAME_SUCCESS = "GET_BREEDS_BY_NAME_SUCCESS";
export const GET_BREEDS_BY_NAME_ERROR = "GET_BREEDS_BY_NAME_ERROR";
export const GET_BREED_BY_ID_SUCCESS = "GET_BREED_BY_ID_SUCCESS";
export const GET_BREED_BY_ID_ERROR = "GET_BREED_BY_ID_ERROR";

//Temperament types
export const LOADING_DB_TEMPS = "LOADING_DB_TEMPS";
export const CREATE_TEMP_DB_SUCCESS = "CREATE_TEMP_DB_SUCCESS";
export const CREATE_TEMP_DB_ERROR = "CREATE_TEMP_DB_ERROR";
export const GET_ALL_TEMPS_SUCESS = "GET_ALL_TEMPS_SUCESS";
export const GET_ALL_TEMPS_ERROR = "GET_ALL_TEMPS_SUCESS";
export const GET_TEMP_BY_ID = "GET_TEMP_BY_ID";
